### ISSUE TITLE
question: ModuleNotFoundError

### ISSUE THREAD

**Issue by 985zhangguoxu** [kinredon/Harmonious-Teacher#2]
Thanks for your works. I successed install cvpods. When I entered "CUDA_VISIBLE_DEVICES=0 pods_train --dir . --dist-url "tcp://127.0.0.1:29007" --num-gpus 1 OUTPUT_DIR 'outputs/ht_c2f'" , there was a error as follow:

Traceback (most recent call last):
  File "/home/dell/student_zhong/zgx/harmteacher/cvpods/tools/train_net.py", line 29, in <module>
    from cvpods.engine import (RUNNERS, default_argument_parser, default_setup,
  File "/home/dell/student_zhong/zgx/harmteacher/cvpods/cvpods/engine/__init__.py", line 3, in <module>
    from .hooks import *
  File "/home/dell/student_zhong/zgx/harmteacher/cvpods/cvpods/engine/hooks.py", line 19, in <module>
    from cvpods.evaluation.testing import flatten_results_dict
  File "/home/dell/student_zhong/zgx/harmteacher/cvpods/cvpods/evaluation/__init__.py", line 8, in <module>
    from .citypersons_evaluation import CityPersonsEvaluator
  File "/home/dell/student_zhong/zgx/harmteacher/cvpods/cvpods/evaluation/citypersons_evaluation.py", line 20, in <module>
    from cvpods.data.datasets.coco import convert_to_coco_json
  File "/home/dell/student_zhong/zgx/harmteacher/cvpods/cvpods/data/__init__.py", line 13, in <module>
    from . import datasets, samplers  # isort:skip
  File "/home/dell/student_zhong/zgx/harmteacher/cvpods/cvpods/data/datasets/__init__.py", line 23, in <module>
    from .city_car_faster import CityCarFasterDataset
ModuleNotFoundError: No module named 'cvpods.data.datasets.city_car_faster'

**Comment by kinredon** [comment]
Thanks for your attention. This error is caused by missing a dataset file. To fix this error, just delete this line https://github.com/kinredon/Harmonious-Teacher/blob/184f3890547422225dee4145e8c4c1ca8d5bf718/cvpods/cvpods/data/datasets/__init__.py#L23
